options(monitora.qfield.somente_funcoes=TRUE);source('monitora_planejamento_amostral.R',encoding='UTF-8');MQ_CONFIG<-mq_legacy_defaults() # Regressão da interface pública 1.0.2
suppressPackageStartupMessages(library(sf))
r<-tempfile();dir.create(r);n<-0;ok<-function(name,v){stopifnot(isTRUE(v));n<<-n+1;cat('PASS',name,'\n')};fails<-function(e)inherits(try(force(e),silent=TRUE),'try-error')
c<-MQ_CONFIG;c$perfil<-'personalizado';c$estratificar_vegetacao<-FALSE;c$politica_insuficiencia<-'usar_disponiveis';c$parametros_protocolo<-list(transecto_m=50,grade_m=c(100,100),direcoes=character(),distancias_viarias_m=numeric());c<-mq_protocol(c);mq_validate_config(c)
ok('personalizado_sem_regras_campestres',length(c$direcoes_campo)==0&&length(c$distancias_viarias_m)==0&&is.na(c$distancia_min_m))
g<-st_as_sf(data.frame(chave_grade=letters[1:12],id_grade=1:12,categoria='grade',x=1:12,y=1:12),coords=c('x','y'),crs=31980)
for(k in 0:2){p<-g[seq_len(k),];z<-mq_select(p,c,r);ok(paste0('pequena_area_',k),sum(z$categoria=='prioritario')==min(k,1)&&sum(z$categoria=='alternativo')==max(0,k-1))}
g$mq_viavel_vias<-c(rep(TRUE,6),rep(FALSE,6));z<-mq_select(g,c,r);ok('quantitativos_limitados_a_disponiveis',sum(z$categoria=='prioritario')==3&&sum(z$categoria=='alternativo')==3&&all(z$categoria[7:12]=='grade'))
a<-data.table::fread(file.path(r,'selecao_quantidades.csv'));ok('deficit_reportado',identical(a$deficit,c(0L,3L))&&all(a$denominador_grade_AE==12))
cs<-c;cs$politica_insuficiencia<-'bloquear';ok('estrito_preservado',fails(mq_select(g,cs)))
cc<-MQ_CONFIG;ok('perfil_campestre_adaptavel',!fails(mq_validate_config(cc)))
cc<-c;cc$estratificar_vegetacao<-TRUE;ok('cotas_vegetacao_adaptaveis',!fails(mq_validate_config(cc)))
cc<-c;cc$estratificar_por_atributos<-TRUE;cc$cotas_atributos<-list(setor=data.frame(classe='a',percentual=100));ok('cotas_atributos_adaptaveis',!fails(mq_validate_config(cc)))
rev<-mq_select(g[12:1,],c);ok('ordem_independente',identical(z$categoria,rev$categoria[12:1]))
h<-g;h$categoria[1:4]<-'alternativo';c2<-c;c2$prioritarios<-list(n=5,percentual=NULL);c2$alternativos<-list(n=4,percentual=NULL);zz<-mq_select(h,c2);ok('historico_reservado',all(zz$categoria[1:4]=='alternativo')&&sum(zz$categoria=='prioritario')==2)
h$categoria[7]<-'prioritario';ok('historico_inviavel_nao_reaproveitado',fails(mq_select(h,c2)))
c3<-c;c3$prioritarios<-list(n=0,percentual=NULL);c3$alternativos<-list(n=8,percentual=NULL);zz<-mq_select(g,c3);ok('somente_alternativos',sum(zz$categoria=='alternativo')==6&&sum(zz$categoria=='prioritario')==0)
c4<-c;c4$prioritarios<-list(n=2,percentual=NULL);c4$alternativos<-list(n=2,percentual=NULL);zz<-mq_select(g,c4);ok('nao_excede_quantidade_pedida',sum(zz$categoria!='grade')==4)
ok('grade_posicoes_preservadas',identical(st_geometry(g),st_geometry(z))&&identical(g$id_grade,z$id_grade))
cat('TOTAL',n,'PASS\n')
