# Instalação real de pacote R mínimo em repositório/biblioteca temporários, sem rede.
options(monitora.qfield.somente_funcoes=TRUE)
before<-search();source('monitora_planejamento_amostral.R',encoding='UTF-8');MQ_CONFIG<-mq_legacy_defaults() # Regressão da interface pública 1.0.2
checks<-character();ok<-function(name,value){stopifnot(isTRUE(value));checks<<-c(checks,name);cat('PASS ',name,'\n',sep='')}
ok('somente_funcoes_nao_anexa_pacotes',identical(before,search()))
ok('lpSolve_na_lista_completa',length(MQ_PACOTES)==15L&&'lpSolve'%in%MQ_PACOTES)
ok('repositorio_padrao_https',identical(unname(mq_repos_pacotes(NULL)),'https://cloud.r-project.org'))
ok('repositorio_configurado_preservado',identical(mq_repos_pacotes(c(CRAN='https://exemplo.invalid',local='file:///tmp/repo')),c(CRAN='https://exemplo.invalid',local='file:///tmp/repo')))
ok('espelho_indefinido_resolvido',all(mq_repos_pacotes(c(CRAN='@CRAN@',outro='',ausente=NA_character_))=='https://cloud.r-project.org'))
run<-function(){
 root<-tempfile('deps_');dir.create(root);lib<-file.path(root,'lib');dir.create(lib)
 repo<-file.path(root,'repo');contrib<-file.path(repo,'src','contrib');dir.create(contrib,recursive=TRUE)
 pkg<-'monitoraTestDeps';src<-file.path(root,pkg);dir.create(src);dir.create(file.path(src,'R'))
 writeLines(c('Package: monitoraTestDeps','Version: 0.0.1','Title: Teste Local de Dependencias','Description: Pacote minimo temporario para verificar instalacao e carregamento.','Author: Teste Monitora','Maintainer: Teste Monitora <teste@example.org>','License: GPL-3'),file.path(src,'DESCRIPTION'))
 writeLines('export(marcador)',file.path(src,'NAMESPACE'))
 writeLines(c('marcador <- function() 42L','.onAttach <- function(libname,pkgname) if (isTRUE(getOption("monitora.test.falha_carga"))) stop("falha simulada de carga")'),file.path(src,'R','teste.R'))
 wd<-getwd();oldlib<-.libPaths();oldopts<-options();counter<-new.env();counter$n<-0L
 on.exit({
   if(paste0('package:',pkg)%in%search())detach(paste0('package:',pkg),character.only=TRUE,unload=TRUE)
   if(pkg%in%loadedNamespaces())unloadNamespace(pkg)
   untrace('install.packages',where=asNamespace('utils'));setwd(wd);.libPaths(oldlib)
   options(oldopts);options(monitora.test.falha_carga=NULL);unlink(root,recursive=TRUE)
 },add=TRUE)
 setwd(root);utils::tar(file.path(contrib,paste0(pkg,'_0.0.1.tar.gz')),files=pkg,compression='gzip',tar='internal');setwd(wd)
 tools::write_PACKAGES(contrib,type='source');.libPaths(c(lib,oldlib))
 url<-paste0(if(.Platform$OS.type=='windows')'file:///'else 'file://',normalizePath(repo,winslash='/'))
 options(repos=c(CRAN=url),pkgType='source')
 trace('install.packages',tracer=function()counter$n<-counter$n+1L,where=asNamespace('utils'),print=FALSE)
 ok('pacote_inicialmente_ausente',!requireNamespace(pkg,quietly=TRUE))
 warns<-character();withCallingHandlers(mq_preparar_pacotes(pkg),warning=function(w){warns<<-c(warns,conditionMessage(w));invokeRestart('muffleWarning')})
 ok('carga_sem_avisos_de_mascaramento',!length(warns))
 ok('ausente_instalado_e_carregado',counter$n==1L&&paste0('package:',pkg)%in%search()&&getExportedValue(pkg,'marcador')()==42L)
 ok('instalacao_na_biblioteca_isolada',normalizePath(find.package(pkg))==normalizePath(file.path(lib,pkg)))
 mq_preparar_pacotes(c(pkg,pkg));ok('disponivel_nao_reinstalado',counter$n==1L)
 repos_before<-getOption('repos');err<-tryCatch(suppressWarnings(mq_preparar_pacotes('monitoraPacoteInexistenteTeste')),error=identity)
 ok('falha_instalacao_detectada',inherits(err,'error')&&grepl('continua indisponível',conditionMessage(err),fixed=TRUE))
 ok('opcoes_repositorio_preservadas',identical(repos_before,getOption('repos')))
 detach(paste0('package:',pkg),character.only=TRUE,unload=FALSE);options(monitora.test.falha_carga=TRUE)
 err<-tryCatch(mq_preparar_pacotes(pkg),error=identity)
 ok('falha_carregamento_explicita',inherits(err,'error')&&grepl('Não foi possível carregar',conditionMessage(err),fixed=TRUE))
 options(monitora.test.falha_carga=FALSE);mq_preparar_pacotes(pkg)
 ok('retomada_reaproveita_instalacao',counter$n==2L&&paste0('package:',pkg)%in%search())
}
run();cat('TOTAL ',length(checks),' PASS\n',sep='')
