options(monitora.qfield.somente_funcoes=TRUE);source('qfield/monitora_criar_qfield.R',encoding='UTF-8');suppressPackageStartupMessages(library(sf))
r<-tempfile();dir.create(r);n<-0;ok<-function(name,v){stopifnot(isTRUE(v));n<<-n+1;cat('PASS',name,'\n')};fails<-function(x)inherits(try(force(x),silent=TRUE),'try-error')
c<-MQ_CONFIG;c$perfil<-'ilha';ci<-mq_protocol(c);mq_validate_config(ci)
ok('ilha_padrao_25_30',ci$transecto_m==25&&identical(ci$grade_m,c(30,30)))
ok('ilha_referencia_experimental',ci$referencia_ilha$distancia_referencia_m==30&&identical(ci$referencia_ilha$direcoes_referencia,c('N','L','S','O')))
ok('ilha_nao_herda_afastamentos_campestres',length(ci$distancias_viarias_m)==0&&length(ci$direcoes_campo)==0&&is.na(ci$distancia_min_m))
c$parametros_protocolo<-list(transecto_m=35,grade_m=c(50,60));z<-mq_protocol(c);ok('sobrescrita_explicita',z$transecto_m==35&&identical(z$grade_m,c(50,60)))
c$padrao_ilha$distancia_referencia_m<--1;ok('referencia_invalida_bloqueia',fails(mq_protocol(c)))
c<-MQ_CONFIG;cc<-mq_protocol(c);ok('campestre_inalterado',cc$transecto_m==50&&all(cc$grade_m==156.25)&&cc$distancias_viarias_m[['estradas_terra']]==50)
rect<-function(x,y,w)st_polygon(list(rbind(c(x,y),c(x+w,y),c(x+w,y+w),c(x,y+w),c(x,y))))
ae<-st_sf(geometry=st_sfc(rect(5e5,8e6,100),crs=31985));u<-st_sf(cnuc='A',nomeuc='UC teste',geometry=st_sfc(st_multipolygon(list(unclass(rect(5e5-1000,8e6-1000,5000)),unclass(rect(6e5,8e6,10000)))),crs=31985));layers<-list(list(x=u,papel='limites_uc',nome='UC'));orig<-st_as_binary(st_geometry(u))
z<-mq_uc_image_parts(ae,layers,c,r);ok('remoto_excluido_contexto',nrow(z)==1&&st_bbox(z)[['xmax']]==504000)
ok('componente_inteiro_nao_buffer_PA',as.numeric(st_area(z))==25e6)
ok('UC_original_preservada',identical(orig,st_as_binary(st_geometry(u))))
c$contexto_uc<-'integral';unlink(file.path(r,'contexto_uc.gpkg'));z<-mq_uc_image_parts(ae,layers,c,r);ok('contexto_integral_opcional',nrow(z)==2)
z<-mq_uc_image_parts(ae,list(),c,r);ok('sem_UC_sem_partes',nrow(z)==0)
# grade_id do piloto liga PA e grade sem substituir rótulo original.
g<-st_as_sf(data.frame(grid_id=c('N1','N2'),x=c(500000,500030),y=8000000),coords=c('x','y'),crs=31985);p<-g[1,];p$pa_id<-'PA-001';l<-list(list(x=g,papel='grade_amostral',nome='grade_amostral',label='grid_id'),list(x=p,papel='PA_priorit',nome='PA_priorit',label='pa_id'));out<-mq_pa_aliases(l,r)
ok('grid_id_compartilhado',out[[1]]$x$codigo_pa[1]==out[[2]]$x$codigo_pa[1])
ok('id_original_preservado',out[[2]]$x$pa_id=='PA-001'&&identical(st_geometry(p),st_geometry(out[[2]]$x)))
l[[2]]$x<-st_set_geometry(l[[2]]$x,st_geometry(g[2,]));ok('mesmo_id_geometria_conflitante_bloqueia',fails(mq_pa_aliases(l,r)))
# AE válida no GEOS, com vértice repetido que o S2 rejeita.
inp<-tempfile();dir.create(inp);coords<-rbind(c(500000,8000000),c(500100,8000000),c(500100,8000000),c(500100,8000100),c(500000,8000100),c(500000,8000000));a<-st_sf(geometry=st_sfc(st_polygon(list(coords)),crs=31985));st_write(a,file.path(inp,'areas_elegiveis.gpkg'),quiet=TRUE);sc<-tempfile();dir.create(sc);rd<-mq_read(inp,sc);ok('uniao_metrica_vertices_repetidos',nrow(rd$ae)==1&&abs(as.numeric(st_area(st_transform(rd$ae,31985)))-10000)<.01)
p<-g;p$pa_id<-c('PA-001','PA-002');p$grid_id[2]<-NA_character_;l[[2]]$x<-p;out<-mq_pa_aliases(l,r);ok('grid_id_parcial_nao_desvincula_validos',out[[1]]$x$codigo_pa[1]==out[[2]]$x$codigo_pa[1]&&out[[1]]$x$codigo_pa[2]!=out[[2]]$x$codigo_pa[2])
z<-mq_mb_labels(data.frame(id=1:5),c(12L,0L,4L,NA_integer_,999L),data.frame(class_id=c(12L,4L),class_name_pt_br=c('Formação Campestre','Formação Savânica')));ok('mapbiomas_pendente_nao_apaga_validos',identical(z$mb_status,c('obtido','codigo_sem_legenda','obtido','sem_dado','codigo_sem_legenda'))&&identical(z$mb_codigo,c(12L,0L,4L,NA_integer_,999L)))
cat('TOTAL_ILHA',n,'PASS\n')
